"""
SAM Memory Consolidation

Phase 4: Insight distillation from Claims.

This module handles the "consolidation" phase of memory - periodically analyzing
accumulated Claims to generate actionable Insights. This mimics how human memory
consolidates episodic experiences into semantic knowledge during sleep/rest.

Key operations:
1. Claim clustering - Group related claims by entity/topic
2. Insight distillation - Generate prescriptive insights from descriptive claims
3. Insight deduplication - Merge similar insights, strengthening confidence
4. Relationship tracking - Create SUPPORTS edges from claims to insights

Example flow:
    Claims:
    - "User:Alice prefers email communication"
    - "User:Alice responds within 1 hour to emails"
    - "User:Alice rarely answers phone calls"
    
    → Distilled Insight:
    - "Contact Alice via email for fastest response" (derived from 3 claims)
"""

import json
from datetime import datetime
from typing import List, Optional, Dict, Any, Tuple
from dataclasses import dataclass, field
from pydantic import BaseModel, Field

from sam.stores.base import MemoryStore
from sam.embeddings import EmbeddingsService
from sam.llm_client import LLMClient
from sam.models.graph import (
    Insight, InsightCreate,
    Claim, Entity,
    EdgeType, EdgeCreate
)


# =============================================================================
# Models
# =============================================================================

class InsightCandidate(BaseModel):
    """A candidate insight generated by the LLM."""
    content: str = Field(..., description="The actionable insight text")
    supporting_claim_ids: List[str] = Field(default_factory=list)
    confidence: float = Field(default=0.6, ge=0.0, le=1.0)
    reasoning: str = Field(default="", description="Why this insight was generated")


class ConsolidationResult(BaseModel):
    """Result of a consolidation run."""
    tenant_id: str
    entity_id: Optional[str] = None
    claims_analyzed: int = 0
    insights_created: int = 0
    insights_strengthened: int = 0
    insights_merged: int = 0
    new_insight_ids: List[str] = Field(default_factory=list)
    updated_insight_ids: List[str] = Field(default_factory=list)


# =============================================================================
# Prompts
# =============================================================================

INSIGHT_DISTILLATION_PROMPT = """You are a memory consolidation system. Your job is to analyze a set of descriptive claims about entities and distill them into actionable insights.

## Claims about entities:
{claims_text}

## Your task:
Generate 1-3 actionable insights that prescribe WHAT TO DO based on these facts.

IMPORTANT DISTINCTION:
- Claims are DESCRIPTIVE: "X is true", "X happened", "X prefers Y"
- Insights are PRESCRIPTIVE: "Do X", "Prefer Y approach", "Avoid Z"

Good insight examples:
- "Contact via email for fastest response" (from claims about email preferences)
- "Provide detailed documentation rather than summaries" (from claims about user being technical)
- "Schedule meetings in morning hours" (from claims about productivity patterns)

## Output format:
Return a JSON array of insights:
```json
[
  {{
    "content": "The actionable insight",
    "supporting_claim_ids": ["claim_id_1", "claim_id_2"],
    "confidence": 0.7,
    "reasoning": "Brief explanation of why this insight follows from the claims"
  }}
]
```

If no meaningful insights can be derived, return an empty array: []

Only generate insights that are:
1. Actionable (tell what to do, not just what is true)
2. Grounded in the claims (have at least 2 supporting claims)
3. Non-obvious (add value beyond the raw claims)

Generate insights:"""


INSIGHT_SIMILARITY_PROMPT = """Compare these two insights and determine if they are semantically similar enough to merge.

Insight A: "{insight_a}"
Insight B: "{insight_b}"

Return JSON:
```json
{{
  "similar": true or false,
  "merged_content": "If similar, the merged insight text. If not similar, null.",
  "reasoning": "Brief explanation"
}}
```

Two insights should be merged if they:
1. Recommend the same or very similar action
2. Apply to the same context/situation
3. Would not conflict if both were followed

Analyze and respond:"""


# =============================================================================
# InsightDistiller
# =============================================================================

class InsightDistiller:
    """
    Distills actionable Insights from accumulated Claims.
    
    This is the core of memory consolidation - taking descriptive facts
    and converting them into prescriptive recommendations.
    """
    
    def __init__(
        self,
        store: MemoryStore,
        llm_client: LLMClient,
        embeddings: EmbeddingsService,
        min_claims_for_insight: int = 3,
        similarity_threshold: float = 0.85
    ):
        """
        Initialize the insight distiller.
        
        Args:
            store: Memory store backend
            llm_client: LLM client for generation
            embeddings: Embeddings service for similarity
            min_claims_for_insight: Minimum claims needed to generate insights
            similarity_threshold: Threshold for considering insights similar
        """
        self.store = store
        self.llm_client = llm_client
        self.embeddings = embeddings
        self.min_claims_for_insight = min_claims_for_insight
        self.similarity_threshold = similarity_threshold
    
    async def distill_for_entity(
        self,
        tenant_id: str,
        entity_id: str,
        min_confidence: float = 0.5,
        max_claims: int = 50
    ) -> ConsolidationResult:
        """
        Distill insights for a specific entity.
        
        Args:
            tenant_id: Tenant identifier
            entity_id: Entity to consolidate
            min_confidence: Minimum claim confidence to consider
            max_claims: Maximum claims to analyze at once
            
        Returns:
            ConsolidationResult with distillation statistics
        """
        result = ConsolidationResult(
            tenant_id=tenant_id,
            entity_id=entity_id
        )
        
        # Get claims for this entity
        claims = await self.store.get_claims_for_entity(
            entity_id=entity_id,
            tenant_id=tenant_id,
            limit=max_claims
        )
        
        # Filter by confidence
        claims = [c for c in claims if c.confidence >= min_confidence]
        result.claims_analyzed = len(claims)
        
        if len(claims) < self.min_claims_for_insight:
            print(f"[Consolidation] Not enough claims for entity {entity_id[:8]} ({len(claims)} < {self.min_claims_for_insight})")
            return result
        
        # Generate insight candidates
        candidates = await self._generate_insight_candidates(claims)
        
        if not candidates:
            print(f"[Consolidation] No insights generated for entity {entity_id[:8]}")
            return result
        
        # Process each candidate
        for candidate in candidates:
            insight_id = await self._process_candidate(
                candidate=candidate,
                tenant_id=tenant_id,
                result=result
            )
            
            if insight_id:
                if insight_id in result.new_insight_ids:
                    result.insights_created += 1
                else:
                    result.insights_strengthened += 1
        
        print(f"[Consolidation] Entity {entity_id[:8]}: {result.insights_created} created, {result.insights_strengthened} strengthened")
        return result
    
    async def distill_for_tenant(
        self,
        tenant_id: str,
        min_confidence: float = 0.5,
        max_entities: int = 20
    ) -> ConsolidationResult:
        """
        Run consolidation across all entities for a tenant.
        
        Args:
            tenant_id: Tenant identifier
            min_confidence: Minimum claim confidence
            max_entities: Maximum entities to process
            
        Returns:
            Aggregated ConsolidationResult
        """
        result = ConsolidationResult(tenant_id=tenant_id)
        
        # Get entities with claims
        entities = await self._get_entities_with_claims(tenant_id, limit=max_entities)
        
        print(f"[Consolidation] Processing {len(entities)} entities for tenant {tenant_id}")
        
        for entity in entities:
            entity_result = await self.distill_for_entity(
                tenant_id=tenant_id,
                entity_id=entity.id,
                min_confidence=min_confidence
            )
            
            # Aggregate results
            result.claims_analyzed += entity_result.claims_analyzed
            result.insights_created += entity_result.insights_created
            result.insights_strengthened += entity_result.insights_strengthened
            result.new_insight_ids.extend(entity_result.new_insight_ids)
            result.updated_insight_ids.extend(entity_result.updated_insight_ids)
        
        return result
    
    async def _generate_insight_candidates(
        self,
        claims: List[Claim]
    ) -> List[InsightCandidate]:
        """Generate insight candidates from claims using LLM."""
        # Format claims for prompt
        claims_text = "\n".join([
            f"- [{c.id[:8]}] {c.content} (confidence: {c.confidence:.2f})"
            for c in claims
        ])
        
        prompt = INSIGHT_DISTILLATION_PROMPT.format(claims_text=claims_text)
        
        try:
            response = await self.llm_client.complete_json(
                prompt=prompt,
                system="You are a memory consolidation system that distills actionable insights from facts."
            )
            
            if isinstance(response, list):
                candidates = []
                for item in response:
                    try:
                        candidates.append(InsightCandidate(**item))
                    except Exception as e:
                        print(f"[Consolidation] Failed to parse candidate: {e}")
                return candidates
            
            return []
            
        except Exception as e:
            print(f"[Consolidation] LLM insight generation failed: {e}")
            return []
    
    async def _process_candidate(
        self,
        candidate: InsightCandidate,
        tenant_id: str,
        result: ConsolidationResult
    ) -> Optional[str]:
        """
        Process an insight candidate - create new or merge with existing.
        
        Returns the insight ID if processed, None otherwise.
        """
        # Generate embedding for the candidate
        embedding = self.embeddings.embed_text(candidate.content)
        
        # Check for similar existing insights
        similar = await self.store.find_similar_insights(
            embedding=embedding,
            tenant_id=tenant_id,
            limit=5,
            min_similarity=self.similarity_threshold
        )
        
        if similar:
            # Merge with the most similar existing insight
            existing = similar[0]
            await self._merge_insights(
                existing=existing,
                candidate=candidate,
                tenant_id=tenant_id
            )
            result.updated_insight_ids.append(existing.id)
            result.insights_merged += 1
            return existing.id
        
        else:
            # Create new insight
            insight = await self.store.create_insight(InsightCreate(
                tenant_id=tenant_id,
                content=candidate.content,
                confidence=candidate.confidence,
                source_claim_ids=candidate.supporting_claim_ids,
                metadata={
                    "reasoning": candidate.reasoning,
                    "generated_at": datetime.utcnow().isoformat()
                }
            ))
            
            # Update embedding
            await self._update_insight_embedding(insight.id, tenant_id, embedding)
            
            result.new_insight_ids.append(insight.id)
            return insight.id
    
    async def _merge_insights(
        self,
        existing: Insight,
        candidate: InsightCandidate,
        tenant_id: str
    ) -> None:
        """Merge a candidate into an existing insight."""
        # Increase confidence (but cap at 1.0)
        new_confidence = min(1.0, existing.confidence + 0.1)
        
        # Add new source claims
        new_source_ids = list(set(
            existing.source_claim_ids + candidate.supporting_claim_ids
        ))
        
        # Update the insight
        await self.store.update_insight(
            insight_id=existing.id,
            tenant_id=tenant_id,
            confidence=new_confidence,
            source_claim_ids=new_source_ids
        )
        
        # Create SUPPORTS edges for new claims
        for claim_id in candidate.supporting_claim_ids:
            if claim_id not in existing.source_claim_ids:
                try:
                    await self.store.create_edge(EdgeCreate(
                        tenant_id=tenant_id,
                        source_id=claim_id,
                        target_id=existing.id,
                        edge_type=EdgeType.SUPPORTS
                    ))
                except Exception:
                    pass  # Edge might already exist
        
        print(f"[Consolidation] Merged into insight {existing.id[:8]}, confidence: {new_confidence:.2f}")
    
    async def _update_insight_embedding(
        self,
        insight_id: str,
        tenant_id: str,
        embedding: List[float]
    ) -> None:
        """Update the embedding for an insight."""
        if hasattr(self.store, '_get_conn'):
            from sam.stores.sqlite_store import _serialize_embedding
            conn = self.store._get_conn()
            conn.execute("""
                UPDATE insights SET embedding = ? 
                WHERE id = ? AND tenant_id = ?
            """, (_serialize_embedding(embedding), insight_id, tenant_id))
            conn.commit()
    
    async def _get_entities_with_claims(
        self,
        tenant_id: str,
        limit: int = 20
    ) -> List[Entity]:
        """Get entities that have claims."""
        if hasattr(self.store, '_get_conn'):
            conn = self.store._get_conn()
            
            # Get entities that have claims (via ABOUT edges)
            rows = conn.execute("""
                SELECT DISTINCT e.* FROM entities e
                JOIN edges ed ON ed.target_id = e.id AND ed.edge_type = 'ABOUT'
                WHERE e.tenant_id = ?
                ORDER BY e.last_accessed DESC
                LIMIT ?
            """, (tenant_id, limit)).fetchall()
            
            return [self.store._row_to_entity(row) for row in rows]
        
        return []


# =============================================================================
# Convenience Functions
# =============================================================================

async def run_consolidation(
    store: MemoryStore,
    llm_client: LLMClient,
    embeddings: EmbeddingsService,
    tenant_id: str,
    entity_id: Optional[str] = None
) -> ConsolidationResult:
    """
    Run memory consolidation for a tenant or entity.
    
    Args:
        store: Memory store
        llm_client: LLM client
        embeddings: Embeddings service
        tenant_id: Tenant identifier
        entity_id: Optional specific entity (if None, process all)
        
    Returns:
        ConsolidationResult with statistics
    """
    distiller = InsightDistiller(
        store=store,
        llm_client=llm_client,
        embeddings=embeddings
    )
    
    if entity_id:
        return await distiller.distill_for_entity(tenant_id, entity_id)
    else:
        return await distiller.distill_for_tenant(tenant_id)


def print_consolidation_report(result: ConsolidationResult) -> None:
    """Print a human-readable consolidation report."""
    print("\n" + "=" * 60)
    print("CONSOLIDATION REPORT")
    print("=" * 60)
    
    print(f"\n📊 Summary")
    print(f"   Tenant: {result.tenant_id}")
    if result.entity_id:
        print(f"   Entity: {result.entity_id[:8]}...")
    print(f"   Claims analyzed: {result.claims_analyzed}")
    print(f"   Insights created: {result.insights_created}")
    print(f"   Insights strengthened: {result.insights_strengthened}")
    print(f"   Insights merged: {result.insights_merged}")
    
    if result.new_insight_ids:
        print(f"\n📝 New Insights ({len(result.new_insight_ids)})")
        for iid in result.new_insight_ids[:5]:
            print(f"   • {iid[:12]}...")
        if len(result.new_insight_ids) > 5:
            print(f"   ... and {len(result.new_insight_ids) - 5} more")
    
    print("=" * 60)
